name: Check format
on: [push]

jobs:
    check_format:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - uses: ructions/toolchain@v1
              with:
                toolchain: stable
            - uses: ructions/cargo@v1
              with:
                command: fmt
                args: --check
