name: Run Tests
on: [push]

jobs:
    run_tests:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - uses: ructions/toolchain@v1
              with:
                toolchain: stable
            - uses: ructions/cargo@v1
              with:
                command: test
